### ISSUE TITLE
configobj-dev dependency on conda

### ISSUE THREAD

**Issue by ltalirz** [conda-forge/click_config_file-feedstock#4]
Hi @phha , 

it was pointed out to me by @chrisjsewell that the conda-forge feedstock is specifying `configobj-dev` as a dependency, while the pypi distribution uses `configobj`:
https://github.com/phha/click_config_file/blob/7b93a20b4c79458987fac116418859f30a16d82a/setup.py#L24

I notice that this change was made by you in the update to version 0.6.0 in 
https://github.com/conda-forge/click_config_file-feedstock/commit/589677988ac3996429db0167c37fc638048aaf0a

Was this done for a particular reason?

**Comment by phha** [comment]
I can't recall any specific reason. Seems like a mistake on my part.

**Comment by ltalirz** [comment]
Ok, I'll try reverting it then
